services:
  guidevault:
    image: ghcr.io/shredder5262/guidevault:latest
    container_name: guidevault
    restart: unless-stopped
    ports:
      - "5478:5478"
    environment:
      ASPNETCORE_URLS: "http://+:5478"
      ASPNETCORE_HTTP_PORTS: "5478"

      GUIDEVAULT_DATA: "/data"
      PAGEQUEST__DATA__ROOT: "/data"

      GUIDEVAULT_LIBRARY_PATH: "/data/library"
      PAGEQUEST_LIBRARY_PATH: "/data/library"

      GUIDEVAULT__UPDATES__CHANNEL: "stable"
      GUIDEVAULT__UPDATES__CURRENTIMAGE: "ghcr.io/shredder5262/guidevault:latest"
    volumes:
      - "./guidevault-data:/data"
